export const calculatorText = {
  title: {
    am: "Հաշվիչ",
    ru: "Калькулятор ремонта",
    en: "Renovation Calculator",
  },
  description: {
    am: "Ստացեք 3 սցենարով նախնական արժեքը` հիմնված Երևանի և Հայաստանի շուկայի վրա",
    ru: "Получите предварительную смету в 3 сценариях на базе ориентиров по Еревану и Армении",
    en: "Get a three-scenario estimate based on Yerevan and Armenia pricing benchmarks",
  },
  estimateLabel: {
    am: "Նախնական արժեքային միջակայք",
    ru: "Предварительный диапазон стоимости",
    en: "Preliminary Budget Range",
  },
  estimateNote: {
    am: "Միջակայքը կառուցված է շուկայական նվազագույն, տիպային և բարձր սցենարների վրա։ Վերջնական գինը կհստակեցվի չափագրումից և աշխատանքների ճշգրտումից հետո։",
    ru: "Диапазон построен на рыночных сценариях min / typical / max. Финальная сумма уточняется после замера и фиксации состава работ.",
    en: "The range is based on market min / typical / max scenarios. The final amount is confirmed after measurement and scope review.",
  },
  estimateSummary: {
    am: "Երեք սցենարները օգնում են տեսնել նվազագույն, իրատեսական և ավելի բարդ տարբերակը",
    ru: "Три сценария помогают увидеть минимальный, реалистичный и более сложный бюджет",
    en: "Three scenarios show the minimum, realistic, and high-complexity budget",
  },
  selectedWorksHint: {
    am: "Ընտրեք միայն այն աշխատանքները, որոնք պետք է հաշվել։ Սմետան կհաշվվի միայն ընտրված դիրքերով, առանց հարկի, լոգիստիկայի և այլ project-level հավելավճարների։",
    ru: "Отметьте только те работы, которые нужно посчитать. Смета считается только по выбранным позициям, без этажных, логистических и других project-level надбавок.",
    en: "Select only the works you want to estimate. The estimate is based only on the chosen items, without floor, logistics, or other project-level uplifts.",
  },
  selectedWorksCoverageHint: {
    am: "Եթե դիրքի համար առանձին դաշտ չկա, այն ավտոմատ չի մտնում հաշվարկի մեջ։ Օրինակ` կահույք, տեխնիկա, հեռուստացույց, դեկոր և այլ առանձին համաձայնեցվող իրեր։",
    ru: "Если для позиции нет отдельного поля, она не попадает в автоподсчёт. Например: мебель, техника, телевизоры, декор и другие отдельно согласуемые позиции.",
    en: "If an item has no separate field, it is not included in the automatic estimate. For example: furniture, appliances, TVs, decor, and other separately agreed items.",
  },
  pricingPackageHint: {
    am: "«Բոլոր նյութերը» նշանակում է շինարարական և հարդարման նյութեր վերանորոգման նախահաշվում։ Կահույք, կենցաղային տեխնիկա, հեռուստացույց, տեքստիլ և դեկոր այստեղ չեն մտնում, եթե առանձին նշված չեն։",
    ru: "Пакет «все материалы» означает строительные и отделочные материалы в рамках ремонтной сметы. Мебель, техника, телевизоры, текстиль и декор сюда не входят, если не добавлены отдельно.",
    en: "The “all materials” package means construction and finish materials within the renovation budget. Furniture, appliances, TVs, textiles, and decor are not included unless listed separately.",
  },
  turnkeyHint: {
    am: "Այս հաշվիչում «բանալիով» նշանակում է ամբողջական վերանորոգման ցիկլ մինչև պատրաստ բնակվելու կամ հանձնելու վիճակ, բայց առանց առանձին համաձայնեցվող կահույքի, տեխնիկայի և դեկորի։",
    ru: "В этом калькуляторе «под ключ» означает полный цикл ремонта до состояния готовности к заселению или сдаче, но без отдельно согласуемых позиций: мебели, техники и декора.",
    en: "In this calculator, “turnkey” means a full renovation cycle to move-in or handover readiness, but without separately approved items such as furniture, appliances, or decor.",
  },
  contactHint: {
    am: "Թողեք հեռախոսահամարը, և կուղարկենք ավելի ճշգրիտ հաշվարկ ու աշխատանքների կազմը։",
    ru: "Оставьте номер телефона, и мы подготовим более точный расчет и состав работ.",
    en: "Leave your phone number and we will prepare a more accurate quote and scope.",
  },
  breakdownLabel: {
    am: "Տիպային breakdown",
    ru: "Типовой breakdown",
    en: "Typical Breakdown",
  },
  breakdownSelectedWorksHint: {
    am: "Ընտրված աշխատանքների breakdown-ը ցուցադրում է միայն առանձին դիրքերը և դրանց subtotal-ները։",
    ru: "Breakdown для selected works показывает только отдельные позиции и их subtotal-ы.",
    en: "The selected-works breakdown shows only the chosen line items and their subtotals.",
  },
  breakdownFullRenovationHint: {
    am: "Full-renovation breakdown-ը ցույց է տալիս բազային sqm-package-ը և թույլատրելի project-level ճշգրտումները։",
    ru: "Breakdown full-renovation показывает базовый sqm-package и допустимые project-level корректировки.",
    en: "The full-renovation breakdown shows the base sqm package and allowed project-level adjustments.",
  },
  breakdownEmpty: {
    am: "Ավելացրեք աշխատանք կամ փոխեք սցենարը, որպեսզի breakdown-ը երևա։",
    ru: "Добавьте работу или измените сценарий, чтобы увидеть breakdown.",
    en: "Add a work item or change the scenario to see the breakdown.",
  },
  breakdownProjectAdjustments: {
    am: "Project-level ճշգրտումներ",
    ru: "Project-level корректировки",
    en: "Project-Level Adjustments",
  },
  breakdownLabor: {
    am: "Աշխատանք",
    ru: "Работы",
    en: "Labor",
  },
  breakdownMaterial: {
    am: "Նյութեր",
    ru: "Материалы",
    en: "Materials",
  },
  breakdownPackage: {
    am: "Փաթեթ / ֆիքսված գին",
    ru: "Пакет / фикс",
    en: "Package / Fixed",
  },
  breakdownMinimumOrder: {
    am: "Minimum order",
    ru: "Минимальный заказ",
    en: "Minimum Order",
  },
  breakdownFinal: {
    am: "Կլորացված արդյունք",
    ru: "Округлённый итог",
    en: "Rounded Total",
  },
  breakdownQuantity: {
    am: "Քանակ",
    ru: "Количество",
    en: "Quantity",
  },
  backButton: {
    am: "Հետ",
    ru: "Назад",
    en: "Back",
  },
  nextButton: {
    am: "Հաջորդ քայլը",
    ru: "Следующий шаг",
    en: "Next Step",
  },
  sendButton: {
    am: "Ուղարկել հայտը ճշգրիտ հաշվարկի համար",
    ru: "Отправить заявку на точный расчет",
    en: "Send Request for Exact Quote",
  },
};

export const calculatorScenarioMeta = [
  {
    id: "minimal",
    reserve: 0,
    label: {
      am: "Նվազագույն",
      ru: "Минимальный",
      en: "Minimal",
    },
    note: {
      am: "Սեղմ բյուջե և պարզ սցենար",
      ru: "Сдержанный бюджет и простой сценарий",
      en: "Lean budget and simpler scope",
    },
  },
  {
    id: "realistic",
    reserve: 0,
    label: {
      am: "Իրատեսական",
      ru: "Реалистичный",
      en: "Realistic",
    },
    note: {
      am: "Ամենահավանական միջին սցենար",
      ru: "Наиболее вероятный средний сценарий",
      en: "Most likely mid-range scenario",
    },
  },
  {
    id: "high",
    reserve: 0,
    label: {
      am: "Բարձր",
      ru: "Высокий",
      en: "High",
    },
    note: {
      am: "Բարդություն, ավելի բարձր ծախսեր կամ բարձրակարգ նյութեր",
      ru: "Более сложный объект, повышенные риски или дорогие материалы",
      en: "Higher complexity, risk, or material grade",
    },
  },
];

export const calculatorProgressSteps = [
  {
    step: 1,
    label: {
      am: "Օբյեկտ",
      ru: "Объект",
      en: "Property",
    },
  },
  {
    step: 2,
    label: {
      am: "Ծավալ և փաթեթ",
      ru: "Объем и пакет",
      en: "Scope & Package",
    },
  },
  {
    step: 3,
    label: {
      am: "Մանրամասներ",
      ru: "Детали",
      en: "Details",
    },
  },
  {
    step: 4,
    label: {
      am: "Արժեք և կապ",
      ru: "Смета и связь",
      en: "Estimate & Contact",
    },
  },
];

export const calculatorFields = {
  locationCity: {
    type: "select",
    impact: 5,
    dependency: "always",
    label: {
      am: "Քաղաք / մարզ",
      ru: "Город / регион",
      en: "City / Region",
    },
    options: [
      {
        value: "yerevan",
        label: {
          am: "Երևան",
          ru: "Ереван",
          en: "Yerevan",
        },
      },
      {
        value: "abovyan",
        label: {
          am: "Աբովյան",
          ru: "Абовян",
          en: "Abovyan",
        },
      },
      {
        value: "ejmiatsin",
        label: {
          am: "Էջմիածին",
          ru: "Эчмиадзин",
          en: "Ejmiatsin",
        },
      },
      {
        value: "gyumri",
        label: {
          am: "Գյումրի",
          ru: "Гюмри",
          en: "Gyumri",
        },
      },
      {
        value: "vanadzor",
        label: {
          am: "Վանաձոր",
          ru: "Ванадзор",
          en: "Vanadzor",
        },
      },
      {
        value: "other",
        label: {
          am: "Այլ քաղաք / մարզ",
          ru: "Другой город / регион",
          en: "Other Region",
        },
      },
    ],
  },
  locationDistrict: {
    type: "select",
    impact: 2,
    dependency: "locationCity = yerevan",
    label: {
      am: "Երևանի վարչական շրջան",
      ru: "Район Еревана",
      en: "Yerevan District",
    },
    options: [
      {
        value: "kentron",
        label: {
          am: "Կենտրոն",
          ru: "Кентрон",
          en: "Kentron",
        },
      },
      {
        value: "arabkir",
        label: {
          am: "Արաբկիր",
          ru: "Арабкир",
          en: "Arabkir",
        },
      },
      {
        value: "davtashen",
        label: {
          am: "Դավթաշեն",
          ru: "Давташен",
          en: "Davtashen",
        },
      },
      {
        value: "ajapnyak",
        label: {
          am: "Աջափնյակ",
          ru: "Ачапняк",
          en: "Ajapnyak",
        },
      },
      {
        value: "nor-nork",
        label: {
          am: "Նոր Նորք",
          ru: "Нор Норк",
          en: "Nor Nork",
        },
      },
      {
        value: "malatia-sebastia",
        label: {
          am: "Մալաթիա-Սեբաստիա",
          ru: "Малатия-Себастия",
          en: "Malatia-Sebastia",
        },
      },
      {
        value: "shengavit",
        label: {
          am: "Շենգավիթ",
          ru: "Шенгавит",
          en: "Shengavit",
        },
      },
      {
        value: "avan",
        label: {
          am: "Ավան",
          ru: "Аван",
          en: "Avan",
        },
      },
      {
        value: "kanaker-zeitun",
        label: {
          am: "Քանաքեռ-Զեյթուն",
          ru: "Канакер-Зейтун",
          en: "Kanaker-Zeytun",
        },
      },
      {
        value: "erebuni",
        label: {
          am: "Էրեբունի",
          ru: "Эребуни",
          en: "Erebuni",
        },
      },
      {
        value: "nork-marash",
        label: {
          am: "Նորք-Մարաշ",
          ru: "Норк-Мараш",
          en: "Nork-Marash",
        },
      },
      {
        value: "other",
        label: {
          am: "Այլ",
          ru: "Другой",
          en: "Other",
        },
      },
    ],
  },
  propertyType: {
    type: "choice",
    impact: 4,
    dependency: "always",
    label: {
      am: "Օբյեկտի տեսակը",
      ru: "Тип объекта",
      en: "Property Type",
    },
    options: [
      {
        value: "apartment",
        label: {
          am: "Բնակարան",
          ru: "Квартира",
          en: "Apartment",
        },
      },
      {
        value: "house",
        label: {
          am: "Առանձնատուն",
          ru: "Дом",
          en: "House",
        },
      },
      {
        value: "commercial",
        label: {
          am: "Կոմերցիոն",
          ru: "Коммерческий",
          en: "Commercial",
        },
      },
    ],
  },
  area: {
    type: "range",
    impact: 5,
    dependency: "always",
    label: {
      am: "Ընդհանուր մակերեսը (քմ)",
      ru: "Общая площадь (м²)",
      en: "Total Area (sqm)",
    },
  },
  conditionStage: {
    type: "select",
    impact: 5,
    dependency: "always",
    label: {
      am: "Օբյեկտի վիճակը",
      ru: "Состояние объекта",
      en: "Current Condition",
    },
    options: [
      {
        value: "new-shell",
        label: {
          am: "Նորակառույց, սևագիր",
          ru: "Новостройка, черновая",
          en: "New Building, Shell",
        },
      },
      {
        value: "new-white-box",
        label: {
          am: "Նորակառույց, նախապատրաստված",
          ru: "Новостройка, white box",
          en: "New Building, White Box",
        },
      },
      {
        value: "secondary-empty",
        label: {
          am: "Երկրորդային, դատարկ",
          ru: "Вторичка, пустая",
          en: "Secondary, Empty",
        },
      },
      {
        value: "secondary-lived-in",
        label: {
          am: "Երկրորդային, բնակեցված",
          ru: "Вторичка, с проживанием",
          en: "Secondary, Occupied",
        },
      },
      {
        value: "after-demolition",
        label: {
          am: "Դեմոնտաժից հետո",
          ru: "После демонтажа",
          en: "After Demolition",
        },
      },
    ],
  },
  estimateMode: {
    type: "choice",
    impact: 5,
    dependency: "always",
    label: {
      am: "Ինչպե՞ս հաշվենք",
      ru: "Что считаем",
      en: "What Should We Estimate",
    },
    options: [
      {
        value: "full-renovation",
        label: {
          am: "Ամբողջական վերանորոգում",
          ru: "Полный ремонт",
          en: "Full Renovation",
        },
      },
      {
        value: "selected-works",
        label: {
          am: "Միայն ընտրված աշխատանքներ",
          ru: "Только выбранные работы",
          en: "Selected Works Only",
        },
      },
    ],
  },
  pricingPackage: {
    type: "choice",
    impact: 5,
    dependency: "always",
    label: {
      am: "Ի՞նչ ներառել արժեքի մեջ",
      ru: "Что включить в стоимость",
      en: "What Should Be Included",
    },
    options: [
      {
        value: "labor-only",
        label: {
          am: "Միայն աշխատանք",
          ru: "Только работы",
          en: "Labor Only",
        },
      },
      {
        value: "labor-plus-rough",
        label: {
          am: "Աշխատանք + սև նյութեր",
          ru: "Работы + черновые материалы",
          en: "Labor + Rough Materials",
        },
      },
      {
        value: "labor-plus-all",
        label: {
          am: "Աշխատանք + շինարարական և հարդարման նյութեր",
          ru: "Работы + строительные и отделочные материалы",
          en: "Labor + Construction and Finish Materials",
        },
      },
    ],
  },
  renovationLevel: {
    type: "choice",
    impact: 5,
    dependency: "estimateMode = full-renovation",
    label: {
      am: "Վերանորոգման մակարդակը",
      ru: "Уровень ремонта",
      en: "Renovation Level",
    },
    options: [
      {
        value: "cosmetic",
        label: {
          am: "Կոսմետիկ",
          ru: "Косметический",
          en: "Cosmetic",
        },
      },
      {
        value: "capital",
        label: {
          am: "Կապիտալ",
          ru: "Капитальный",
          en: "Capital",
        },
      },
      {
        value: "premium-turnkey",
        label: {
          am: "Պրեմիում / բանալիով",
          ru: "Премиум / под ключ",
          en: "Premium / Turnkey",
        },
      },
    ],
  },
  wetZonesCount: {
    type: "segment",
    impact: 4,
    dependency: "full-renovation + residential",
    label: {
      am: "Սանհանգույց / խոնավ գոտիներ",
      ru: "Санузлы / мокрые зоны",
      en: "Wet Zones",
    },
    options: [
      {
        value: "1",
        label: {
          am: "1",
          ru: "1",
          en: "1",
        },
      },
      {
        value: "2",
        label: {
          am: "2",
          ru: "2",
          en: "2",
        },
      },
      {
        value: "3plus",
        label: {
          am: "3+",
          ru: "3+",
          en: "3+",
        },
      },
    ],
  },
  engineeringScope: {
    type: "segment",
    impact: 5,
    dependency: "estimateMode = full-renovation",
    label: {
      am: "Ինժեներական համակարգեր",
      ru: "Инженерные системы",
      en: "Engineering Scope",
    },
    options: [
      {
        value: "keep-existing",
        label: {
          am: "Պահպանել գործողը",
          ru: "Оставить текущее",
          en: "Keep Existing",
        },
      },
      {
        value: "partial-replace",
        label: {
          am: "Մասնակի փոխարինում",
          ru: "Частичная замена",
          en: "Partial Replace",
        },
      },
      {
        value: "full-replace",
        label: {
          am: "Լիարժեք փոխարինում",
          ru: "Полная замена",
          en: "Full Replace",
        },
      },
    ],
  },
  replanningNeeded: {
    type: "segment",
    impact: 4,
    dependency: "full-renovation and non-cosmetic",
    label: {
      am: "Պե՞տք է վերապլանավորում",
      ru: "Нужна перепланировка",
      en: "Replanning Needed",
    },
    options: [
      {
        value: "no",
        label: {
          am: "Ոչ",
          ru: "Нет",
          en: "No",
        },
      },
      {
        value: "yes",
        label: {
          am: "Այո",
          ru: "Да",
          en: "Yes",
        },
      },
    ],
  },
  demolitionScope: {
    type: "choice",
    impact: 4,
    dependency: "secondary object or replanning",
    label: {
      am: "Դեմոնտաժի ծավալը",
      ru: "Объем демонтажа",
      en: "Demolition Scope",
    },
    options: [
      {
        value: "none",
        label: {
          am: "Չկա",
          ru: "Нет",
          en: "None",
        },
      },
      {
        value: "light-finish",
        label: {
          am: "Թեթև հարդարանք",
          ru: "Легкий",
          en: "Light Finish",
        },
      },
      {
        value: "medium",
        label: {
          am: "Միջին",
          ru: "Средний",
          en: "Medium",
        },
      },
      {
        value: "heavy-with-walls",
        label: {
          am: "Ծանր, նաև պատեր",
          ru: "Тяжелый, со стенами",
          en: "Heavy With Walls",
        },
      },
    ],
  },
  workModules: {
    type: "multi-select",
    impact: 5,
    dependency: "estimateMode = selected-works",
    label: {
      am: "Ընտրեք աշխատանքները",
      ru: "Выберите работы",
      en: "Choose the Works",
    },
    options: [
      {
        value: "demolition",
        label: {
          am: "Դեմոնտաժ",
          ru: "Демонтаж",
          en: "Demolition",
        },
      },
      {
        value: "electrical",
        label: {
          am: "Էլեկտրամոնտաժ",
          ru: "Электрика",
          en: "Electrical",
        },
      },
      {
        value: "plumbing",
        label: {
          am: "Սանտեխնիկա",
          ru: "Сантехника",
          en: "Plumbing",
        },
      },
      {
        value: "screed",
        label: {
          am: "Ստյաժկա",
          ru: "Стяжка пола",
          en: "Floor Screed",
        },
      },
      {
        value: "tile",
        label: {
          am: "Սալիկապատում",
          ru: "Плитка",
          en: "Tile",
        },
      },
      {
        value: "wall-paint",
        label: {
          am: "Պատերի ներկում",
          ru: "Подготовка и покраска",
          en: "Wall Paint",
        },
      },
      {
        value: "laminate-floor",
        label: {
          am: "Լամինատ",
          ru: "Ламинат",
          en: "Laminate Floor",
        },
      },
    ],
  },
  demolitionArea: {
    type: "number",
    impact: 4,
    dependency: "workModules includes demolition",
    label: {
      am: "Դեմոնտաժի մակերեսը (քմ)",
      ru: "Площадь демонтажа (м²)",
      en: "Demolition Area (sqm)",
    },
    placeholder: {
      am: "Օր.` 25",
      ru: "Напр. 25",
      en: "e.g. 25",
    },
  },
  electricalPoints: {
    type: "number",
    impact: 5,
    dependency: "workModules includes electrical",
    label: {
      am: "Էլեկտրական կետեր (հատ)",
      ru: "Электроточки (шт.)",
      en: "Electrical Points",
    },
    placeholder: {
      am: "Օր.` 25",
      ru: "Напр. 25",
      en: "e.g. 25",
    },
  },
  plumbingPoints: {
    type: "number",
    impact: 4,
    dependency: "workModules includes plumbing",
    label: {
      am: "Փոքր սանտեխնիկական աշխատանքներ / այցեր (հատ)",
      ru: "Мелкие сантехнические задачи / выезды (шт.)",
      en: "Minor Plumbing Jobs / Visits",
    },
    placeholder: {
      am: "Օր.` 1",
      ru: "Напр. 1",
      en: "e.g. 1",
    },
  },
  plumberHours: {
    type: "number",
    impact: 3,
    dependency: "workModules includes plumbing",
    label: {
      am: "Սանտեխնիկի հավելյալ ժամեր",
      ru: "Дополнительные часы сантехника",
      en: "Additional Plumber Hours",
    },
    placeholder: {
      am: "Օր.` 2",
      ru: "Напр. 2",
      en: "e.g. 2",
    },
  },
  screedArea: {
    type: "number",
    impact: 4,
    dependency: "workModules includes screed",
    label: {
      am: "Ստյաժկայի մակերեսը (քմ)",
      ru: "Площадь стяжки (м²)",
      en: "Screed Area (sqm)",
    },
    placeholder: {
      am: "Օր.` 60",
      ru: "Напр. 60",
      en: "e.g. 60",
    },
  },
  tileArea: {
    type: "number",
    impact: 4,
    dependency: "workModules includes tile",
    label: {
      am: "Սալիկի մակերեսը (քմ)",
      ru: "Площадь плитки (м²)",
      en: "Tile Area (sqm)",
    },
    placeholder: {
      am: "Օր.` 18",
      ru: "Напр. 18",
      en: "e.g. 18",
    },
  },
  paintArea: {
    type: "number",
    impact: 3,
    dependency: "workModules includes wall-paint",
    label: {
      am: "Ներկման մակերեսը (քմ)",
      ru: "Площадь покраски (м²)",
      en: "Paint Area (sqm)",
    },
    placeholder: {
      am: "Օր.` 140",
      ru: "Напр. 140",
      en: "e.g. 140",
    },
  },
  laminateArea: {
    type: "number",
    impact: 4,
    dependency: "workModules includes laminate-floor",
    label: {
      am: "Լամինատի մակերեսը (քմ)",
      ru: "Площадь ламината (м²)",
      en: "Laminate Area (sqm)",
    },
    placeholder: {
      am: "Օր.` 45",
      ru: "Напр. 45",
      en: "e.g. 45",
    },
  },
  plinthLength: {
    type: "number",
    impact: 2,
    dependency: "workModules includes laminate-floor",
    label: {
      am: "Պլինտուսի երկարությունը (գծ.մ.)",
      ru: "Длина плинтуса (п.м.)",
      en: "Plinth Length (lm)",
    },
    placeholder: {
      am: "Օր.` 32",
      ru: "Напр. 32",
      en: "e.g. 32",
    },
  },
  floorNumber: {
    type: "number",
    impact: 2,
    dependency: "propertyType = apartment",
    label: {
      am: "Հարկ",
      ru: "Этаж",
      en: "Floor",
    },
    placeholder: {
      am: "Օր.` 7",
      ru: "Напр. 7",
      en: "e.g. 7",
    },
  },
  elevator: {
    type: "segment",
    impact: 3,
    dependency: "apartment and floor > 1",
    label: {
      am: "Կա՞ վերելակ",
      ru: "Есть ли лифт",
      en: "Elevator Available",
    },
    options: [
      {
        value: "yes",
        label: {
          am: "Այո",
          ru: "Да",
          en: "Yes",
        },
      },
      {
        value: "no",
        label: {
          am: "Ոչ",
          ru: "Нет",
          en: "No",
        },
      },
    ],
  },
  accessLevel: {
    type: "segment",
    impact: 3,
    dependency: "always",
    label: {
      am: "Մուտք և լոգիստիկա",
      ru: "Доступ и логистика",
      en: "Access & Logistics",
    },
    options: [
      {
        value: "easy",
        label: {
          am: "Հեշտ",
          ru: "Легко",
          en: "Easy",
        },
      },
      {
        value: "standard",
        label: {
          am: "Ստանդարտ",
          ru: "Стандарт",
          en: "Standard",
        },
      },
      {
        value: "difficult",
        label: {
          am: "Դժվար",
          ru: "Сложно",
          en: "Difficult",
        },
      },
    ],
  },
  urgency: {
    type: "segment",
    impact: 2,
    dependency: "advanced",
    label: {
      am: "Ժամկետի շտապություն",
      ru: "Срочность",
      en: "Urgency",
    },
    options: [
      {
        value: "standard",
        label: {
          am: "Ստանդարտ",
          ru: "Стандарт",
          en: "Standard",
        },
      },
      {
        value: "urgent",
        label: {
          am: "Շտապ",
          ru: "Срочно",
          en: "Urgent",
        },
      },
      {
        value: "very-urgent",
        label: {
          am: "Շատ շտապ",
          ru: "Очень срочно",
          en: "Very Urgent",
        },
      },
    ],
  },
  name: {
    label: {
      am: "Ձեր անունը",
      ru: "Ваше имя",
      en: "Your Name",
    },
    placeholder: {
      am: "Անուն",
      ru: "Имя",
      en: "Name",
    },
  },
  phone: {
    label: {
      am: "Հեռախոսահամար",
      ru: "Номер телефона",
      en: "Phone Number",
    },
    placeholder: {
      am: "+374 ...",
      ru: "+374 ...",
      en: "+374 ...",
    },
  },
  comment: {
    label: {
      am: "Մեկնաբանություն",
      ru: "Комментарий",
      en: "Comment",
    },
    placeholder: {
      am: "Օր.` ուզվող ժամկետ, դիզայն, լուսանկարների հղում կամ հատուկ պայմաններ",
      ru: "Напр.: желаемый срок, пожелания по дизайну, ссылка на фото или особенности объекта",
      en: "e.g. desired timing, design notes, links to photos, or special site conditions",
    },
  },
};

export const calculatorWorkModuleFieldMap = {
  demolition: ["demolitionArea"],
  electrical: ["electricalPoints"],
  plumbing: ["plumbingPoints", "plumberHours"],
  screed: ["screedArea"],
  tile: ["tileArea"],
  "wall-paint": ["paintArea"],
  "laminate-floor": ["laminateArea", "plinthLength"],
};

const createI18nValue = (am, ru, en) => ({ am, ru, en });

const createScenarioValues = (minimal, realistic, high) => ({
  minimal,
  realistic,
  high,
});

export const calculatorRateCatalog = {
  electric_point: {
    key: "electric_point",
    label: createI18nValue("Էլեկտրակետ", "Электроточка", "Electrical Point"),
    unit: "point",
    pricingMode: "hybrid",
    laborMin: 2500,
    laborTypical: 3000,
    laborMax: 5000,
    materialMin: 1500,
    materialTypical: 2455,
    materialMax: 3500,
    totalMin: 4000,
    totalTypical: 5455,
    totalMax: 8500,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "2026 Armenia market benchmark from the latest Yerevan electrical point synthesis.",
  },
  tile_work_m2: {
    key: "tile_work_m2",
    label: createI18nValue("Սալիկապատում", "Плитка / керамогранит", "Tile / Porcelain Work"),
    unit: "m2",
    pricingMode: "hybrid",
    laborMin: 6000,
    laborTypical: 10000,
    laborMax: 15000,
    materialMin: 7000,
    materialTypical: 10000,
    materialMax: 14000,
    totalMin: 13000,
    totalTypical: 16000,
    totalMax: 29000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "2026 Yerevan benchmark for tile labor plus materials per square meter.",
  },
  plumbing_visit: {
    key: "plumbing_visit",
    label: createI18nValue("Սանտեխնիկական այց", "Сантехнический выезд", "Plumbing Visit"),
    unit: "job",
    pricingMode: "minimum_order",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 5000,
    totalTypical: 10000,
    totalMax: 15000,
    minOrderTotal: 10000,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Minor plumbing jobs use a market-backed visit rate with a minimum order floor.",
  },
  plumber_hour: {
    key: "plumber_hour",
    label: createI18nValue("Սանտեխնիկի ժամ", "Час сантехника", "Plumber Hour"),
    unit: "hour",
    pricingMode: "hourly",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 5000,
    totalTypical: 7000,
    totalMax: 10000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Hourly plumbing support rate from the latest Yerevan market sweep.",
  },
  door_install: {
    key: "door_install",
    label: createI18nValue("Դռան տեղադրում", "Монтаж двери", "Door Installation"),
    unit: "door",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 10000,
    totalTypical: 12000,
    totalMax: 18000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "medium",
    sourceNote: "Real-case benchmark kept as the current working market reference for door installation.",
  },
  socket_material: {
    key: "socket_material",
    label: createI18nValue("Վարդակի նյութ", "Материал розетки", "Socket Material"),
    unit: "pcs",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 550,
    totalTypical: 930,
    totalMax: 1500,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Material-only benchmark for simple sockets and switches.",
  },
  breaker_single_phase: {
    key: "breaker_single_phase",
    label: createI18nValue("Միափուլ ավտոմատ", "Однофазный автомат", "Single Phase Breaker"),
    unit: "pcs",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 1320,
    totalTypical: 1800,
    totalMax: 2300,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Material-only market benchmark for a single-phase breaker.",
  },
  led_light: {
    key: "led_light",
    label: createI18nValue("LED լուսավորություն", "LED светильник", "LED Light"),
    unit: "pcs",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 800,
    totalTypical: 1500,
    totalMax: 4000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Simple LED lighting benchmark from Armenia listings.",
  },
  light_profile: {
    key: "light_profile",
    label: createI18nValue("Լուսային պրոֆիլ", "Световой профиль", "Light Profile"),
    unit: "pcs",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 1500,
    totalTypical: 1800,
    totalMax: 2500,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Light profile benchmark from Armenia listing data.",
  },
  gypsum_board_sheet: {
    key: "gypsum_board_sheet",
    label: createI18nValue("Գիպսաստվարաթուղթ", "Лист гипсокартона", "Gypsum Board Sheet"),
    unit: "sheet",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 2200,
    totalTypical: 2700,
    totalMax: 3400,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Material benchmark for standard gypsum board sheets.",
  },
  gypsum_board_moisture_resistant_sheet: {
    key: "gypsum_board_moisture_resistant_sheet",
    label: createI18nValue("Խոնավակայուն գիպսաստվարաթուղթ", "Влагостойкий гипсокартон", "Moisture Resistant Gypsum Board"),
    unit: "sheet",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 3700,
    totalTypical: 3900,
    totalMax: 4100,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Material benchmark for moisture resistant gypsum board sheets.",
  },
  tile_glue_bag_25kg: {
    key: "tile_glue_bag_25kg",
    label: createI18nValue("25 կգ սալիկի սոսինձ", "Плиточный клей 25 кг", "Tile Glue Bag 25kg"),
    unit: "bag",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 5700,
    totalTypical: 6200,
    totalMax: 7000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Material benchmark for 25kg tile adhesive bags.",
  },
  bathroom_fixture_package: {
    key: "bathroom_fixture_package",
    label: createI18nValue("Սանհանգույցի սարքավորումների փաթեթ", "Пакет сантехприборов санузла", "Bathroom Fixture Package"),
    unit: "project",
    pricingMode: "package",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 0,
    totalTypical: 0,
    totalMax: 0,
    minOrderTotal: 0,
    packageTotalMin: 280000,
    packageTotalTypical: 355000,
    packageTotalMax: 500000,
    sourceConfidence: "high",
    sourceNote: "Package benchmark based on the current stacked bathroom installation real-case data.",
  },
  heating_package_small_flat: {
    key: "heating_package_small_flat",
    label: createI18nValue("Փոքր բնակարանի ջեռուցման փաթեթ", "Пакет отопления для небольшой квартиры", "Small Flat Heating Package"),
    unit: "project",
    pricingMode: "package",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 0,
    totalTypical: 0,
    totalMax: 0,
    minOrderTotal: 0,
    packageTotalMin: 450000,
    packageTotalTypical: 650000,
    packageTotalMax: 950000,
    sourceConfidence: "medium",
    sourceNote: "Package benchmark widened for the 2026 Armenia heating market.",
  },
  cosmetic_renovation_m2: {
    key: "cosmetic_renovation_m2",
    label: createI18nValue("Կոսմետիկ վերանորոգում", "Косметический ремонт", "Cosmetic Renovation"),
    unit: "m2",
    pricingMode: "sqm_package",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 45000,
    totalTypical: 55000,
    totalMax: 70000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "2026 Yerevan cosmetic renovation market benchmark per square meter.",
  },
  capital_renovation_m2: {
    key: "capital_renovation_m2",
    label: createI18nValue("Կապիտալ վերանորոգում", "Капитальный ремонт", "Capital Renovation"),
    unit: "m2",
    pricingMode: "sqm_package",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 90000,
    totalTypical: 120000,
    totalMax: 160000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "2026 Yerevan capital renovation market benchmark per square meter.",
  },
  demolition_area_m2: {
    key: "demolition_area_m2",
    label: createI18nValue("Դեմոնտաժ", "Демонтаж", "Demolition"),
    unit: "m2",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 2000,
    totalTypical: 3000,
    totalMax: 4000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    packagePricing: {
      "labor-only": createScenarioValues(2000, 3000, 4000),
      "labor-plus-rough": createScenarioValues(2000, 3000, 4000),
      "labor-plus-all": createScenarioValues(2000, 3000, 4000),
    },
    sourceConfidence: "low",
    sourceNote: "Legacy calculator fallback kept until a new demolition market sample is collected.",
  },
  screed_area_m2: {
    key: "screed_area_m2",
    label: createI18nValue("Ստյաժկա", "Стяжка пола", "Floor Screed"),
    unit: "m2",
    pricingMode: "hybrid",
    laborMin: 3000,
    laborTypical: 4000,
    laborMax: 5000,
    materialMin: 1050,
    materialTypical: 1800,
    materialMax: 2750,
    totalMin: 4050,
    totalTypical: 5800,
    totalMax: 7750,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    packagePricing: {
      "labor-only": createScenarioValues(3000, 4000, 5000),
      "labor-plus-rough": createScenarioValues(4050, 5800, 7750),
      "labor-plus-all": createScenarioValues(4050, 5800, 7750),
    },
    sourceConfidence: "low",
    sourceNote: "Legacy calculator fallback kept until a new screed market sample is collected.",
  },
  paint_work_m2: {
    key: "paint_work_m2",
    label: createI18nValue("Պատերի նախապատրաստում և ներկում", "Подготовка и покраска стен", "Wall Prep and Paint"),
    unit: "m2",
    pricingMode: "hybrid",
    laborMin: 2500,
    laborTypical: 3500,
    laborMax: 4500,
    materialMin: 500,
    materialTypical: 1050,
    materialMax: 1800,
    totalMin: 3000,
    totalTypical: 4550,
    totalMax: 6300,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    packagePricing: {
      "labor-only": createScenarioValues(2500, 3500, 4500),
      "labor-plus-rough": createScenarioValues(3000, 4550, 6300),
      "labor-plus-all": createScenarioValues(3625, 5775, 8550),
    },
    sourceConfidence: "low",
    sourceNote: "Legacy calculator fallback kept until a new painting market sample is collected.",
  },
  laminate_floor_m2: {
    key: "laminate_floor_m2",
    label: createI18nValue("Լամինատ", "Ламинат", "Laminate Floor"),
    unit: "m2",
    pricingMode: "hybrid",
    laborMin: 2000,
    laborTypical: 2750,
    laborMax: 3500,
    materialMin: 100,
    materialTypical: 220,
    materialMax: 420,
    totalMin: 2100,
    totalTypical: 2970,
    totalMax: 3920,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    packagePricing: {
      "labor-only": createScenarioValues(2000, 2750, 3500),
      "labor-plus-rough": createScenarioValues(2100, 2970, 3920),
      "labor-plus-all": createScenarioValues(4000, 6325, 9450),
    },
    sourceConfidence: "low",
    sourceNote: "Legacy calculator fallback kept until a new laminate market sample is collected.",
  },
  plinth_install_lm: {
    key: "plinth_install_lm",
    label: createI18nValue("Պլինտուս", "Плинтус", "Plinth"),
    unit: "lm",
    pricingMode: "hybrid",
    laborMin: 700,
    laborTypical: 1000,
    laborMax: 1200,
    materialMin: 14,
    materialTypical: 50,
    materialMax: 96,
    totalMin: 714,
    totalTypical: 1050,
    totalMax: 1296,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    packagePricing: {
      "labor-only": createScenarioValues(700, 1000, 1200),
      "labor-plus-rough": createScenarioValues(714, 1050, 1296),
      "labor-plus-all": createScenarioValues(1120, 1800, 2520),
    },
    sourceConfidence: "low",
    sourceNote: "Legacy calculator fallback kept until a new plinth market sample is collected.",
  },
};

export const calculatorSelectedWorkFieldCatalog = {
  demolitionArea: {
    rateKey: "demolition_area_m2",
  },
  electricalPoints: {
    rateKey: "electric_point",
  },
  plumbingPoints: {
    rateKey: "plumbing_visit",
  },
  plumberHours: {
    rateKey: "plumber_hour",
  },
  screedArea: {
    rateKey: "screed_area_m2",
  },
  tileArea: {
    rateKey: "tile_work_m2",
  },
  paintArea: {
    rateKey: "paint_work_m2",
  },
  laminateArea: {
    rateKey: "laminate_floor_m2",
  },
  plinthLength: {
    rateKey: "plinth_install_lm",
  },
};

export const calculatorFullRenovationRateCatalog = {
  cosmetic: "cosmetic_renovation_m2",
  capital: "capital_renovation_m2",
  "premium-turnkey": "capital_renovation_m2",
};

export const calculatorProjectAdjustmentLabels = {
  cityCoefficient: createI18nValue("Քաղաքի գործակից", "Коэффициент города", "City Coefficient"),
  districtCoefficient: createI18nValue("Շրջանի գործակից", "Коэффициент района", "District Coefficient"),
  propertyCoefficient: createI18nValue("Օբյեկտի գործակից", "Коэффициент объекта", "Property Coefficient"),
  conditionCoefficient: createI18nValue("Վիճակի գործակից", "Коэффициент состояния", "Condition Coefficient"),
  engineeringCoefficient: createI18nValue("Ինժեներական համակարգեր", "Инженерные системы", "Engineering Scope"),
  wetZoneCoefficient: createI18nValue("Խոնավ գոտիներ", "Мокрые зоны", "Wet Zones"),
  accessCoefficient: createI18nValue("Մուտք և լոգիստիկա", "Доступ и логистика", "Access & Logistics"),
  urgencyCoefficient: createI18nValue("Շտապություն", "Срочность", "Urgency"),
  demolitionScope: createI18nValue("Դեմոնտաժ", "Демонтаж", "Demolition"),
  replanning: createI18nValue("Վերապլանավորում", "Перепланировка", "Replanning"),
  cityLogistics: createI18nValue("Քաղաքային լոգիստիկա", "Городская логистика", "City Logistics"),
  floorSurcharge: createI18nValue("Հարկայնության հավելավճար", "Надбавка за этаж", "Floor Surcharge"),
};

export const calculatorPricingConfig = {
  roundingStep: 500,
  packageCoefficients: {
    "labor-only": {
      minimal: 0.72,
      realistic: 0.78,
      high: 0.84,
    },
    "labor-plus-rough": {
      minimal: 1,
      realistic: 1,
      high: 1,
    },
    "labor-plus-all": {
      minimal: 1.38,
      realistic: 1.52,
      high: 1.72,
    },
  },
  cityCoefficients: {
    yerevan: 1,
    abovyan: 0.98,
    ejmiatsin: 0.97,
    gyumri: 0.92,
    vanadzor: 0.94,
    other: 0.96,
  },
  districtCoefficients: {
    kentron: 1.04,
    arabkir: 1.03,
    davtashen: 1,
    ajapnyak: 0.99,
    "nor-nork": 1,
    "malatia-sebastia": 0.98,
    shengavit: 0.99,
    avan: 1,
    "kanaker-zeitun": 1.01,
    erebuni: 0.99,
    "nork-marash": 1.02,
    other: 1,
  },
  propertyCoefficients: {
    apartment: {
      minimal: 1,
      realistic: 1,
      high: 1,
    },
    house: {
      minimal: 1.1,
      realistic: 1.12,
      high: 1.16,
    },
    commercial: {
      minimal: 1.08,
      realistic: 1.12,
      high: 1.18,
    },
  },
  conditionCoefficients: {
    "new-shell": {
      minimal: 1,
      realistic: 1,
      high: 1,
    },
    "new-white-box": {
      minimal: 0.93,
      realistic: 0.95,
      high: 0.97,
    },
    "secondary-empty": {
      minimal: 1.08,
      realistic: 1.12,
      high: 1.15,
    },
    "secondary-lived-in": {
      minimal: 1.12,
      realistic: 1.18,
      high: 1.22,
    },
    "after-demolition": {
      minimal: 0.98,
      realistic: 1,
      high: 1.03,
    },
  },
  wetZoneCoefficients: {
    "1": {
      minimal: 1,
      realistic: 1,
      high: 1,
    },
    "2": {
      minimal: 1.06,
      realistic: 1.08,
      high: 1.1,
    },
    "3plus": {
      minimal: 1.12,
      realistic: 1.15,
      high: 1.18,
    },
  },
  engineeringCoefficients: {
    "keep-existing": {
      minimal: 1,
      realistic: 1,
      high: 1,
    },
    "partial-replace": {
      minimal: 1.06,
      realistic: 1.09,
      high: 1.12,
    },
    "full-replace": {
      minimal: 1.12,
      realistic: 1.16,
      high: 1.22,
    },
  },
  accessCoefficients: {
    easy: {
      minimal: 1,
      realistic: 1,
      high: 1,
    },
    standard: {
      minimal: 1.01,
      realistic: 1.02,
      high: 1.03,
    },
    difficult: {
      minimal: 1.05,
      realistic: 1.07,
      high: 1.1,
    },
  },
  urgencyCoefficients: {
    standard: {
      minimal: 1,
      realistic: 1,
      high: 1,
    },
    urgent: {
      minimal: 1.05,
      realistic: 1.08,
      high: 1.1,
    },
    "very-urgent": {
      minimal: 1.12,
      realistic: 1.15,
      high: 1.18,
    },
  },
  replanningCosts: {
    apartment: {
      minimal: 120000,
      realistic: 200000,
      high: 320000,
    },
    house: {
      minimal: 180000,
      realistic: 280000,
      high: 420000,
    },
    commercial: {
      minimal: 200000,
      realistic: 320000,
      high: 480000,
    },
  },
  demolitionScopeRates: {
    none: {
      minimal: 0,
      realistic: 0,
      high: 0,
    },
    "light-finish": {
      minimal: 1200,
      realistic: 1800,
      high: 2500,
    },
    medium: {
      minimal: 2200,
      realistic: 3000,
      high: 4000,
    },
    "heavy-with-walls": {
      minimal: 3500,
      realistic: 5000,
      high: 6500,
    },
  },
  cityLogistics: {
    yerevan: {
      minimal: 0,
      realistic: 0,
      high: 0,
    },
    abovyan: {
      minimal: 15000,
      realistic: 30000,
      high: 50000,
    },
    ejmiatsin: {
      minimal: 20000,
      realistic: 35000,
      high: 60000,
    },
    gyumri: {
      minimal: 70000,
      realistic: 120000,
      high: 180000,
    },
    vanadzor: {
      minimal: 60000,
      realistic: 100000,
      high: 150000,
    },
    other: {
      minimal: 50000,
      realistic: 90000,
      high: 140000,
    },
  },
  floorSurcharge: {
    withElevator: {
      minimal: 3000,
      realistic: 5000,
      high: 7000,
    },
    noElevator: {
      minimal: 8000,
      realistic: 12000,
      high: 18000,
    },
  },
};

export const initialCalculatorForm = {
  locationCity: "yerevan",
  locationDistrict: "kentron",
  propertyType: "apartment",
  area: 60,
  conditionStage: "new-shell",
  estimateMode: "full-renovation",
  pricingPackage: "labor-plus-rough",
  renovationLevel: "capital",
  wetZonesCount: "1",
  engineeringScope: "partial-replace",
  replanningNeeded: "no",
  demolitionScope: "none",
  workModules: [],
  demolitionArea: 25,
  electricalPoints: 25,
  plumbingPoints: 1,
  plumberHours: 0,
  screedArea: 60,
  tileArea: 18,
  paintArea: 140,
  laminateArea: 45,
  plinthLength: 32,
  floorNumber: 4,
  elevator: "yes",
  accessLevel: "standard",
  urgency: "standard",
  name: "",
  phone: "",
  comment: "",
};

export const initialCalculatorState = {
  step: 1,
  form: initialCalculatorForm,
};
