// Single source of truth for calculator benchmarks, rate tables, and pricing adjustments.

const createI18nValue = (am, ru, en) => ({ am, ru, en });

const createScenarioValues = (minimal, realistic, high) => ({
  minimal,
  realistic,
  high,
});

export const calculatorRateCatalog = {
  electric_point: {
    key: "electric_point",
    label: createI18nValue("Էլեկտրակետ", "Электроточка", "Electrical Point"),
    unit: "point",
    pricingMode: "hybrid",
    laborMin: 2500,
    laborTypical: 3000,
    laborMax: 5000,
    materialMin: 1500,
    materialTypical: 2455,
    materialMax: 3500,
    totalMin: 4000,
    totalTypical: 5455,
    totalMax: 8500,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "2026 Armenia market benchmark from the latest Yerevan electrical point synthesis.",
  },
  tile_work_m2: {
    key: "tile_work_m2",
    label: createI18nValue("Սալիկապատում", "Плитка / керамогранит", "Tile / Porcelain Work"),
    unit: "m2",
    pricingMode: "hybrid",
    laborMin: 6000,
    laborTypical: 10000,
    laborMax: 15000,
    materialMin: 7000,
    materialTypical: 10000,
    materialMax: 14000,
    totalMin: 13000,
    totalTypical: 16000,
    totalMax: 29000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "2026 Yerevan benchmark for tile labor plus materials per square meter.",
  },
  plumbing_visit: {
    key: "plumbing_visit",
    label: createI18nValue("Սանտեխնիկական այց", "Сантехнический выезд", "Plumbing Visit"),
    unit: "job",
    pricingMode: "minimum_order",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 5000,
    totalTypical: 10000,
    totalMax: 15000,
    minOrderTotal: 10000,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Minor plumbing jobs use a market-backed visit rate with a minimum order floor.",
  },
  plumber_hour: {
    key: "plumber_hour",
    label: createI18nValue("Սանտեխնիկի ժամ", "Час сантехника", "Plumber Hour"),
    unit: "hour",
    pricingMode: "hourly",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 5000,
    totalTypical: 7000,
    totalMax: 10000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Hourly plumbing support rate from the latest Yerevan market sweep.",
  },
  cosmetic_renovation_m2: {
    key: "cosmetic_renovation_m2",
    label: createI18nValue("Կոսմետիկ վերանորոգում", "Косметический ремонт", "Cosmetic Renovation"),
    unit: "m2",
    pricingMode: "sqm_package",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 45000,
    totalTypical: 55000,
    totalMax: 70000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "2026 Yerevan cosmetic renovation market benchmark per square meter.",
  },
  capital_renovation_m2: {
    key: "capital_renovation_m2",
    label: createI18nValue("Կապիտալ վերանորոգում", "Капитальный ремонт", "Capital Renovation"),
    unit: "m2",
    pricingMode: "sqm_package",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 90000,
    totalTypical: 120000,
    totalMax: 160000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "2026 Yerevan capital renovation market benchmark per square meter.",
  },
  demolition_area_m2: {
    key: "demolition_area_m2",
    label: createI18nValue("Դեմոնտաժ", "Демонтаж", "Demolition"),
    unit: "m2",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 2000,
    totalTypical: 3000,
    totalMax: 4000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    packagePricing: {
      "labor-only": createScenarioValues(2000, 3000, 4000),
      "labor-plus-rough": createScenarioValues(2000, 3000, 4000),
      "labor-plus-all": createScenarioValues(2000, 3000, 4000),
    },
    sourceConfidence: "low",
    sourceNote: "Legacy calculator fallback kept until a new demolition market sample is collected.",
  },
  screed_area_m2: {
    key: "screed_area_m2",
    label: createI18nValue("Ստյաժկա", "Стяжка пола", "Floor Screed"),
    unit: "m2",
    pricingMode: "hybrid",
    laborMin: 3000,
    laborTypical: 4000,
    laborMax: 5000,
    materialMin: 1050,
    materialTypical: 1800,
    materialMax: 2750,
    totalMin: 4050,
    totalTypical: 5800,
    totalMax: 7750,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    packagePricing: {
      "labor-only": createScenarioValues(3000, 4000, 5000),
      "labor-plus-rough": createScenarioValues(4050, 5800, 7750),
      "labor-plus-all": createScenarioValues(4050, 5800, 7750),
    },
    sourceConfidence: "low",
    sourceNote: "Legacy calculator fallback kept until a new screed market sample is collected.",
  },
  paint_work_m2: {
    key: "paint_work_m2",
    label: createI18nValue("Պատերի նախապատրաստում և ներկում", "Подготовка и покраска стен", "Wall Prep and Paint"),
    unit: "m2",
    pricingMode: "hybrid",
    laborMin: 2500,
    laborTypical: 3500,
    laborMax: 4500,
    materialMin: 500,
    materialTypical: 1050,
    materialMax: 1800,
    totalMin: 3000,
    totalTypical: 4550,
    totalMax: 6300,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    packagePricing: {
      "labor-only": createScenarioValues(2500, 3500, 4500),
      "labor-plus-rough": createScenarioValues(3000, 4550, 6300),
      "labor-plus-all": createScenarioValues(3625, 5775, 8550),
    },
    sourceConfidence: "low",
    sourceNote: "Legacy calculator fallback kept until a new painting market sample is collected.",
  },
  laminate_floor_m2: {
    key: "laminate_floor_m2",
    label: createI18nValue("Լամինատ", "Ламинат", "Laminate Floor"),
    unit: "m2",
    pricingMode: "hybrid",
    laborMin: 2000,
    laborTypical: 2750,
    laborMax: 3500,
    materialMin: 100,
    materialTypical: 220,
    materialMax: 420,
    totalMin: 2100,
    totalTypical: 2970,
    totalMax: 3920,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    packagePricing: {
      "labor-only": createScenarioValues(2000, 2750, 3500),
      "labor-plus-rough": createScenarioValues(2100, 2970, 3920),
      "labor-plus-all": createScenarioValues(4000, 6325, 9450),
    },
    sourceConfidence: "low",
    sourceNote: "Legacy calculator fallback kept until a new laminate market sample is collected.",
  },
  plinth_install_lm: {
    key: "plinth_install_lm",
    label: createI18nValue("Պլինտուս", "Плинтус", "Plinth"),
    unit: "lm",
    pricingMode: "hybrid",
    laborMin: 700,
    laborTypical: 1000,
    laborMax: 1200,
    materialMin: 14,
    materialTypical: 50,
    materialMax: 96,
    totalMin: 714,
    totalTypical: 1050,
    totalMax: 1296,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    packagePricing: {
      "labor-only": createScenarioValues(700, 1000, 1200),
      "labor-plus-rough": createScenarioValues(714, 1050, 1296),
      "labor-plus-all": createScenarioValues(1120, 1800, 2520),
    },
    sourceConfidence: "low",
    sourceNote: "Legacy calculator fallback kept until a new plinth market sample is collected.",
  },
};

// Reference-only benchmarks are kept separate so the active calculator catalog contains only
// rates that are wired into current user-facing flows.
export const calculatorReferenceRateCatalog = {
  door_install: {
    key: "door_install",
    label: createI18nValue("Դռան տեղադրում", "Монтаж двери", "Door Installation"),
    unit: "door",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 10000,
    totalTypical: 12000,
    totalMax: 18000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "medium",
    sourceNote: "Real-case benchmark kept as the current working market reference for door installation.",
  },
  socket_material: {
    key: "socket_material",
    label: createI18nValue("Վարդակի նյութ", "Материал розетки", "Socket Material"),
    unit: "pcs",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 550,
    totalTypical: 930,
    totalMax: 1500,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Material-only benchmark for simple sockets and switches.",
  },
  breaker_single_phase: {
    key: "breaker_single_phase",
    label: createI18nValue("Միափուլ ավտոմատ", "Однофазный автомат", "Single Phase Breaker"),
    unit: "pcs",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 1320,
    totalTypical: 1800,
    totalMax: 2300,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Material-only market benchmark for a single-phase breaker.",
  },
  led_light: {
    key: "led_light",
    label: createI18nValue("LED լուսավորություն", "LED светильник", "LED Light"),
    unit: "pcs",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 800,
    totalTypical: 1500,
    totalMax: 4000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Simple LED lighting benchmark from Armenia listings.",
  },
  light_profile: {
    key: "light_profile",
    label: createI18nValue("Լուսային պրոֆիլ", "Световой профиль", "Light Profile"),
    unit: "pcs",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 1500,
    totalTypical: 1800,
    totalMax: 2500,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Light profile benchmark from Armenia listing data.",
  },
  gypsum_board_sheet: {
    key: "gypsum_board_sheet",
    label: createI18nValue("Գիպսաստվարաթուղթ", "Лист гипсокартона", "Gypsum Board Sheet"),
    unit: "sheet",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 2200,
    totalTypical: 2700,
    totalMax: 3400,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Material benchmark for standard gypsum board sheets.",
  },
  gypsum_board_moisture_resistant_sheet: {
    key: "gypsum_board_moisture_resistant_sheet",
    label: createI18nValue("Խոնավակայուն գիպսաստվարաթուղթ", "Влагостойкий гипсокартон", "Moisture Resistant Gypsum Board"),
    unit: "sheet",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 3700,
    totalTypical: 3900,
    totalMax: 4100,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Material benchmark for moisture resistant gypsum board sheets.",
  },
  tile_glue_bag_25kg: {
    key: "tile_glue_bag_25kg",
    label: createI18nValue("25 կգ սալիկի սոսինձ", "Плиточный клей 25 кг", "Tile Glue Bag 25kg"),
    unit: "bag",
    pricingMode: "unit",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 5700,
    totalTypical: 6200,
    totalMax: 7000,
    minOrderTotal: 0,
    packageTotalMin: 0,
    packageTotalTypical: 0,
    packageTotalMax: 0,
    sourceConfidence: "high",
    sourceNote: "Material benchmark for 25kg tile adhesive bags.",
  },
  bathroom_fixture_package: {
    key: "bathroom_fixture_package",
    label: createI18nValue("Սանհանգույցի սարքավորումների փաթեթ", "Пакет сантехприборов санузла", "Bathroom Fixture Package"),
    unit: "project",
    pricingMode: "package",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 0,
    totalTypical: 0,
    totalMax: 0,
    minOrderTotal: 0,
    packageTotalMin: 280000,
    packageTotalTypical: 355000,
    packageTotalMax: 500000,
    sourceConfidence: "high",
    sourceNote: "Package benchmark based on the current stacked bathroom installation real-case data.",
  },
  heating_package_small_flat: {
    key: "heating_package_small_flat",
    label: createI18nValue("Փոքր բնակարանի ջեռուցման փաթեթ", "Пакет отопления для небольшой квартиры", "Small Flat Heating Package"),
    unit: "project",
    pricingMode: "package",
    laborMin: 0,
    laborTypical: 0,
    laborMax: 0,
    materialMin: 0,
    materialTypical: 0,
    materialMax: 0,
    totalMin: 0,
    totalTypical: 0,
    totalMax: 0,
    minOrderTotal: 0,
    packageTotalMin: 450000,
    packageTotalTypical: 650000,
    packageTotalMax: 950000,
    sourceConfidence: "medium",
    sourceNote: "Package benchmark widened for the 2026 Armenia heating market.",
  },
};

export const calculatorSelectedWorkFieldCatalog = {
  demolitionArea: {
    rateKey: "demolition_area_m2",
  },
  electricalPoints: {
    rateKey: "electric_point",
  },
  plumbingPoints: {
    rateKey: "plumbing_visit",
  },
  plumberHours: {
    rateKey: "plumber_hour",
  },
  screedArea: {
    rateKey: "screed_area_m2",
  },
  tileArea: {
    rateKey: "tile_work_m2",
  },
  paintArea: {
    rateKey: "paint_work_m2",
  },
  laminateArea: {
    rateKey: "laminate_floor_m2",
  },
  plinthLength: {
    rateKey: "plinth_install_lm",
  },
};

export const calculatorFullRenovationRateCatalog = {
  cosmetic: "cosmetic_renovation_m2",
  capital: "capital_renovation_m2",
  "premium-turnkey": "capital_renovation_m2",
};

export const calculatorProjectAdjustmentLabels = {
  cityCoefficient: createI18nValue("Քաղաքի գործակից", "Коэффициент города", "City Coefficient"),
  propertyCoefficient: createI18nValue("Օբյեկտի գործակից", "Коэффициент объекта", "Property Coefficient"),
  conditionCoefficient: createI18nValue("Վիճակի գործակից", "Коэффициент состояния", "Condition Coefficient"),
  engineeringCoefficient: createI18nValue("Ինժեներական համակարգեր", "Инженерные системы", "Engineering Systems"),
  wetZoneCoefficient: createI18nValue("Խոնավ գոտիներ", "Мокрые зоны", "Wet Zones"),
  urgencyCoefficient: createI18nValue("Շտապություն", "Срочность", "Urgency"),
  demolitionScope: createI18nValue("Ապամոնտաժում", "Демонтаж", "Demolition"),
  replanning: createI18nValue("Վերահատակագծում", "Перепланировка", "Replanning"),
  cityLogistics: createI18nValue("Քաղաքային լոգիստիկա", "Городская логистика", "City Logistics"),
  floorSurcharge: createI18nValue("Հարկի հավելավճար", "Надбавка за этаж", "Floor Surcharge"),
};

export const calculatorPricingConfig = {
  roundingStep: 500,
  packageCoefficients: {
    "labor-only": {
      minimal: 0.72,
      realistic: 0.78,
      high: 0.84,
    },
    "labor-plus-rough": {
      minimal: 1,
      realistic: 1,
      high: 1,
    },
    "labor-plus-all": {
      minimal: 1.38,
      realistic: 1.52,
      high: 1.72,
    },
  },
  cityCoefficients: {
    yerevan: 1,
    abovyan: 0.98,
    ejmiatsin: 0.97,
    gyumri: 0.92,
    vanadzor: 0.94,
    other: 0.96,
  },
  propertyCoefficients: {
    apartment: {
      minimal: 1,
      realistic: 1,
      high: 1,
    },
    house: {
      minimal: 1.1,
      realistic: 1.12,
      high: 1.16,
    },
    commercial: {
      minimal: 1.08,
      realistic: 1.12,
      high: 1.18,
    },
  },
  conditionCoefficients: {
    "new-shell": {
      minimal: 1,
      realistic: 1,
      high: 1,
    },
    "new-white-box": {
      minimal: 0.93,
      realistic: 0.95,
      high: 0.97,
    },
    "secondary-empty": {
      minimal: 1.08,
      realistic: 1.12,
      high: 1.15,
    },
    "secondary-lived-in": {
      minimal: 1.12,
      realistic: 1.18,
      high: 1.22,
    },
    "after-demolition": {
      minimal: 0.98,
      realistic: 1,
      high: 1.03,
    },
  },
  wetZoneCoefficients: {
    "1": {
      minimal: 1,
      realistic: 1,
      high: 1,
    },
    "2": {
      minimal: 1.06,
      realistic: 1.08,
      high: 1.1,
    },
    "3plus": {
      minimal: 1.12,
      realistic: 1.15,
      high: 1.18,
    },
  },
  engineeringCoefficients: {
    "keep-existing": {
      minimal: 1,
      realistic: 1,
      high: 1,
    },
    "partial-replace": {
      minimal: 1.06,
      realistic: 1.09,
      high: 1.12,
    },
    "full-replace": {
      minimal: 1.12,
      realistic: 1.16,
      high: 1.22,
    },
  },
  urgencyCoefficients: {
    standard: {
      minimal: 1,
      realistic: 1,
      high: 1,
    },
    urgent: {
      minimal: 1.05,
      realistic: 1.08,
      high: 1.1,
    },
    "very-urgent": {
      minimal: 1.12,
      realistic: 1.15,
      high: 1.18,
    },
  },
  replanningCosts: {
    apartment: {
      minimal: 120000,
      realistic: 200000,
      high: 320000,
    },
    house: {
      minimal: 180000,
      realistic: 280000,
      high: 420000,
    },
    commercial: {
      minimal: 200000,
      realistic: 320000,
      high: 480000,
    },
  },
  demolitionScopeRates: {
    none: {
      minimal: 0,
      realistic: 0,
      high: 0,
    },
    "light-finish": {
      minimal: 1200,
      realistic: 1800,
      high: 2500,
    },
    medium: {
      minimal: 2200,
      realistic: 3000,
      high: 4000,
    },
    "heavy-with-walls": {
      minimal: 3500,
      realistic: 5000,
      high: 6500,
    },
  },
  cityLogistics: {
    yerevan: {
      minimal: 0,
      realistic: 0,
      high: 0,
    },
    abovyan: {
      minimal: 15000,
      realistic: 30000,
      high: 50000,
    },
    ejmiatsin: {
      minimal: 20000,
      realistic: 35000,
      high: 60000,
    },
    gyumri: {
      minimal: 70000,
      realistic: 120000,
      high: 180000,
    },
    vanadzor: {
      minimal: 60000,
      realistic: 100000,
      high: 150000,
    },
    other: {
      minimal: 50000,
      realistic: 90000,
      high: 140000,
    },
  },
  floorSurcharge: {
    withElevator: {
      minimal: 3000,
      realistic: 5000,
      high: 7000,
    },
    noElevator: {
      minimal: 8000,
      realistic: 12000,
      high: 18000,
    },
  },
};
